server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/click {
        proxy_pass http://click-service:8080/api/click;
    }
    location /api/player {
        proxy_pass http://player-service:8080/api/player;
    }
    location /api/auth {
        proxy_pass http://player-service:8080/api/auth;
    }
    location /api/store {
        proxy_pass http://store-service:8080/api/store;
    }
    location /api/admin {
        proxy_pass http://admin-service:8080/api/admin;
    }
}